apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: pfe-app
data:
  POSTGRES_HOST: "postgres.pfe-infra.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "pfe_db"
  REDIS_HOST: "redis.pfe-infra.svc.cluster.local"
  REDIS_PORT: "6379"
  DEBUG: "false"
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  LANGCHAIN_TRACING_V2: "true"
  LANGCHAIN_PROJECT: "pfe-pricewatch"