"""make offre nom nullable

Revision ID: 4ae3bfeb970c
Revises: 6febc31d0072
Create Date: 2026-04-02 14:23:38.362973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ae3bfeb970c'
down_revision: Union[str, None] = '6febc31d0072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('offres_normalisees', 'nom',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offres_normalisees', 'nom',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('categories', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
