"""initial schema

Revision ID: 6febc31d0072
Revises: 
Create Date: 2026-04-01 21:08:56.211510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6febc31d0072'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('journal_audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_utilisateur', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('valeurs_avant', sa.JSON(), nullable=True),
    sa.Column('valeurs_apres', sa.JSON(), nullable=True),
    sa.Column('horodatage', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sites_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('est_actif', sa.Boolean(), nullable=True),
    sa.Column('scraper_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_organisation', sa.String(length=100), nullable=False),
    sa.Column('est_actif', sa.Boolean(), nullable=True),
    sa.Column('plan_abonnement', sa.String(length=20), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('id_parent', sa.Integer(), nullable=True),
    sa.Column('url_categorie_brute', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_parent'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrappeurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('site_source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['site_source_id'], ['sites_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('alertes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('periode_surveillance', sa.Date(), nullable=True),
    sa.Column('type_evenement', sa.String(length=50), nullable=True),
    sa.Column('liste_categories', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id_utilisateur', sa.Integer(), nullable=True),
    sa.Column('alert', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations_ia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_utilisateur', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('date_debut', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_derniere_activite', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rapports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('id_utilisateur', sa.Integer(), nullable=True),
    sa.Column('titre', sa.String(length=255), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referentiels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_produit', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('marque', sa.String(length=100), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('categorie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages_ia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_utilisateur', sa.Integer(), nullable=True),
    sa.Column('id_conversation', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('contenu', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_conversation'], ['conversations_ia.id'], ),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offres_normalisees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('marque', sa.String(length=100), nullable=True),
    sa.Column('prix_original', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('prix_en_promotion', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('est_en_tete', sa.Boolean(), nullable=True),
    sa.Column('statut_stock', sa.String(length=50), nullable=True),
    sa.Column('url_produit', sa.String(length=500), nullable=True),
    sa.Column('categorie_id', sa.Integer(), nullable=True),
    sa.Column('offre_brute', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('scraper_id', sa.Integer(), nullable=True),
    sa.Column('score_qualite', sa.Float(), nullable=True),
    sa.Column('produit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['referentiels.id'], ),
    sa.ForeignKeyConstraint(['scraper_id'], ['scrappeurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offre_id', sa.Integer(), nullable=True),
    sa.Column('referentiel_id', sa.Integer(), nullable=True),
    sa.Column('score_confluence', sa.Float(), nullable=True),
    sa.Column('statut', sa.String(length=30), nullable=True),
    sa.Column('id_validateur', sa.Integer(), nullable=True),
    sa.Column('date_validation', sa.DateTime(), nullable=True),
    sa.Column('date_proposition', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('commentaire', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_validateur'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['offre_id'], ['offres_normalisees.id'], ),
    sa.ForeignKeyConstraint(['referentiel_id'], ['referentiels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offre_id', sa.Integer(), nullable=True),
    sa.Column('nom', sa.String(length=255), nullable=True),
    sa.Column('marque', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('prix_original', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('prix_promotion', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('stock_status', sa.String(length=50), nullable=True),
    sa.Column('offre_brute', sa.JSON(), nullable=True),
    sa.Column('score_qualite', sa.Float(), nullable=True),
    sa.Column('date_debut_observation', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_fin_observation', sa.DateTime(), nullable=True),
    sa.Column('nb_observations_identiques', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['offre_id'], ['offres_normalisees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('details_criteres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidat_id', sa.Integer(), nullable=True),
    sa.Column('critere', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['candidat_id'], ['candidats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('details_criteres')
    op.drop_table('snapshots')
    op.drop_table('candidats')
    op.drop_table('offres_normalisees')
    op.drop_table('messages_ia')
    op.drop_table('referentiels')
    op.drop_table('rapports')
    op.drop_table('conversations_ia')
    op.drop_table('alertes')
    op.drop_table('utilisateurs')
    op.drop_table('scrappeurs')
    op.drop_table('categories')
    op.drop_table('tenants')
    op.drop_table('sites_source')
    op.drop_table('journal_audit')
    op.drop_table('admins')
    # ### end Alembic commands ###
