apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-postgres
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  postgres-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: PostgreSQL
        type: postgres
        uid: pfe-postgres
        url: postgres.pfe-infra.svc.cluster.local:5432
        user: pfe_user
        jsonData:
          database: pfe_db
          sslmode: disable
          postgresVersion: 1500
          timescaledb: false
          maxOpenConns: 5
          maxIdleConns: 2
          connMaxLifetime: 14400
        secureJsonData:
          password: changeme
        isDefault: false
        editable: true