apiVersion: v1
kind: Namespace
metadata:
  name: pfe-infra
  labels:
    project: pfe-price-monitor
    tier: infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: pfe-app
  labels:
    project: pfe-price-monitor
    tier: application
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    project: pfe-price-monitor
    tier: monitoring