Start-Process powershell -ArgumentList "kubectl port-forward -n kube-system svc/traefik 8888:80"
Start-Process powershell -ArgumentList "kubectl port-forward -n pfe-infra svc/postgres 5432:5432"
Start-Process powershell -ArgumentList "kubectl port-forward -n pfe-app svc/flower-ui 5555:5555"
Start-Process powershell -ArgumentList "kubectl port-forward -n pfe-app svc/playwright 3001:3001"
Start-Process powershell -ArgumentList "kubectl port-forward -n monitoring svc/monitoring-kube-prometheus-prometheus 9090:9090"
Start-Process powershell -ArgumentList "kubectl port-forward -n monitoring svc/monitoring-grafana 3000:80"

Write-Host "Port-forwards actifs :"
Write-Host "  API via Traefik : http://localhost:8888 (Host: api.pfe.local)"
Write-Host "  PostgreSQL      : localhost:5432"
Write-Host "  Flower Celery   : http://localhost:5555"
Write-Host "  Playwright      : http://localhost:3001"
Write-Host "  Prometheus      : http://localhost:9090"
Write-Host "  Grafana         : http://localhost:3000"